# https://hub.docker.com/_/eclipse-mosquitto/tags
MQTT_VERSION: "2.0.18"
MQTT_FRONT_PORT: "8030"
MQTT_EXTERNAL_URL: "mqtt.{{ (DOMAIN_NAME |length > 0) | ternary(DOMAIN_NAME, DEFAULT_DOMAIN_NAME) }}"
MQTT_READ_USER: "reader"
MQTT_RW_USER: "writer"
MQTT_DEFAULT_STATE: stopped

# https://hub.docker.com/r/nodered/node-red/tags
NODERED_VERSION: "3.1.0-18-minimal"
NODERED_FRONT_PORT: "8031"
NODERED_EXTERNAL_URL: "flows.{{ (DOMAIN_NAME |length > 0) | ternary(DOMAIN_NAME, DEFAULT_DOMAIN_NAME) }}"
NODERED_DEFAULT_STATE: stopped

# https://hub.docker.com/r/octoprint/octoprint/tags
OCTOPRINT_VERSION: "1.9.3-minimal"
OCTOPRINT_PORT: "8033"
OCTOPRINT_EXTERNAL_URL: "printers.{{ (DOMAIN_NAME |length > 0) | ternary(DOMAIN_NAME, DEFAULT_DOMAIN_NAME) }}"
OCTOPRINT_DEVICE_0: "/dev/null"
OCTOPRINT_DEVICE_1: "/dev/null"
OCTOPRINT_DEFAULT_STATE: stopped

INSOLANTE_VERSION: "1.4.1"
INSOLANTE_PORT: "8032"
INSOLANTE_URL: "{{ (DOMAIN_NAME |length > 0) | ternary(DOMAIN_NAME, hostvars[inventory_hostname]['ansible_default_ipv4']['address']) }}"
INSOLANTE_EXTERNAL_URL: "pcb.{{ (DOMAIN_NAME |length > 0) | ternary(DOMAIN_NAME, DEFAULT_DOMAIN_NAME) }}"
INSOLANTE_DEFAULT_STATE: stopped
