---
- import_tasks: setup_mqtt.yml
  when: ("domotic" not in SKIP_SERVICES)

- import_tasks: setup_nodered.yml
  when: ("domotic" not in SKIP_SERVICES)

- import_tasks: setup_insolante.yml
  when: ("insolante" not in SKIP_SERVICES)

- import_tasks: setup_octoprint.yml
  when: ("octoprint" not in SKIP_SERVICES)
