---
- name: "Setup insolante directory"
  ansible.builtin.file:
    path: "/{{ DATACORE }}/insolante"
    owner: "{{ USER_NAME }}"
    group: "{{ USER_NAME }}"
    state: directory

- name: "Define insolante_image Arm?"
  ansible.builtin.set_fact:
     insolante_image: "ngargaud/insolante:arm-{{ INSOLANTE_VERSION }}"
  when: ansible_architecture in ["armv7l", "aarch64"]

- name: "Define insolante_image amd64?"
  ansible.builtin.set_fact:
     insolante_image: "ngargaud/insolante:{{ INSOLANTE_VERSION }}"
  when: ansible_architecture in ["amd64", "x86_64"]

- name: "Launch insolante container {{ INSOLANTE_VERSION }}"
  community.general.docker_container:
    name: "insolante"
    image: "{{ insolante_image }}"
    state: "{{ INSOLANTE_DEFAULT_STATE }}"
    restart_policy: always
    timeout: "{{ DOCKER_TIMEOUT }}"
#    ports:
#      - "{{ INSOLANTE_PORT }}:5000"
    env:
      URL: "{{ INSOLANTE_URL }}"
      RPORT: "{{ INSOLANTE_PORT }}"
      DEBUG: "false"
    volumes:
      - "/{{ DATACORE }}/insolante:/opt/core/data"
    labels:
      traefik.enable: "true"
      traefik.http.services.insolante.loadbalancer.server.port: "5000"
      traefik.http.middlewares.https_redirect.redirectscheme.scheme: "https"
      traefik.http.routers.insolante_http.middlewares: "https_redirect"
      traefik.http.routers.insolante_http.rule: "Host(`{{ INSOLANTE_EXTERNAL_URL }}`)"
      traefik.http.routers.insolante_http.service: insolante
      traefik.http.routers.insolante_https.rule: "Host(`{{ INSOLANTE_EXTERNAL_URL }}`)"
      traefik.http.routers.insolante_https.service: insolante
      traefik.http.routers.insolante_https.tls: "true"
      # add this to use traefik as a proxy with tls (http will not be available)
      traefik.http.services.insolante_proxy.loadbalancer.server.port: "5000"
      traefik.http.routers.insolante_proxy.service: insolante_proxy
      traefik.http.routers.insolante_proxy.entrypoints: insolante
      traefik.http.routers.insolante_proxy.rule: "{{ global_proxy_rule }}"
      traefik.http.routers.insolante_proxy.tls: "true"
  when: insolante_image is defined
