---
- name: "Setup datacore directory"
  file:
    path: "/{{ DATACORE }}/octoprint"
    owner: "1000"
    group: "1000"
    state: directory

- name: "List devices in /dev"
  shell: "ls /dev"
  ignore_errors: True
  register: ttyACMx

- name: "Define OCTOPRINT_DEVICE_0 to /dev/ttyACM0"
  set_fact:
     OCTOPRINT_DEVICE_0: "/dev/ttyACM0"
  when: "'ttyACM0' in ttyACMx.stdout_lines"

- name: "Define OCTOPRINT_DEVICE_1 to /dev/ttyACM1"
  set_fact:
     OCTOPRINT_DEVICE_1: "/dev/ttyACM1"
  when: "'ttyACM1' in ttyACMx.stdout_lines"

- name: "Launch octoprint container {{ OCTOPRINT_VERSION }}"
  docker_container:
    name: "octoprint"
    image: "octoprint/octoprint:{{ OCTOPRINT_VERSION }}"
    state: "{{ OCTOPRINT_DEFAULT_STATE }}"
    restart_policy: always
    recreate: yes
    timeout: "{{ DOCKER_TIMEOUT }}"
#    ports:
#      - "{{ OCTOPRINT_PORT }}:5000"
    devices:
      - "{{ OCTOPRINT_DEVICE_0 }}:/dev/ttyACM0"
      - "{{ OCTOPRINT_DEVICE_1 }}:/dev/ttyACM1"
    volumes:
      - "/{{ DATACORE }}/octoprint:/config"
    labels:
      traefik.enable: "true"
      traefik.http.services.octoprint.loadbalancer.server.port: "5000"
      traefik.http.middlewares.https_redirect.redirectscheme.scheme: "https"
      traefik.http.routers.octoprint_http.middlewares: "https_redirect"
      traefik.http.routers.octoprint_http.rule: "Host(`{{ OCTOPRINT_EXTERNAL_URL }}`)"
      traefik.http.routers.octoprint_http.service: octoprint
      traefik.http.routers.octoprint_https.rule: "Host(`{{ OCTOPRINT_EXTERNAL_URL }}`)"
      traefik.http.routers.octoprint_https.service: octoprint
      traefik.http.routers.octoprint_https.tls: "true"
      # add this to use traefik as a proxy with tls (http will not be available)
      traefik.http.services.octoprint_proxy.loadbalancer.server.port: "5000"
      traefik.http.routers.octoprint_proxy.service: octoprint_proxy
      traefik.http.routers.octoprint_proxy.entrypoints: octoprint
      traefik.http.routers.octoprint_proxy.rule: "{{ global_proxy_rule }}"
      traefik.http.routers.octoprint_proxy.tls: "true"
