
[tls.stores]
  [tls.stores.default]
    [tls.stores.default.defaultCertificate]
      keyFile = "/certs/{{ DOMAIN_CERT_KEY_NAME | default('default-key.pem') }}"
      certFile = "/certs/{{ DOMAIN_CERT_NAME | default('default.pem') }}"
