[global]
  sendAnonymousUsage = false

[log]
  level = "INFO"
  format = "common"

# Configuring a buffer of 300 lines to limit writing to the disk too frequently
[accessLog]
  filePath = "/etc/traefik/access.log"
  bufferingSize = 300

################################################################
# Web configuration backend
################################################################
[api]
  insecure = true
  dashboard = true
  debug = true

################################################################
# Entry-points configuration
################################################################
[entryPoints]
  [entryPoints.https]
    address = ":443"
    [entryPoints.https.http.tls]
    {% if TRAEFIK_USE_LETSENCRYPT == true %}
      certResolver = "letsencrypt"
    {% endif %}

  [entryPoints.http]
    address = ":80"

{% for ep in TRAEFIK_ENTRYPOINT_MAP %}
  [entryPoints.{{ ep.name }}]
    address = ":{{ ep.port }}"
{% endfor %}
################################################################
# Docker and ssl providers
################################################################
[providers]
  [providers.docker]
    endpoint = "unix:///var/run/docker.sock"
    exposedbydefault = false
    watch = true

  [providers.file]
    filename = "/etc/traefik/tls-certs.toml"
    watch = true

{% if TRAEFIK_USE_LETSENCRYPT == true %}
################################################################
# Let's encrypt
################################################################
[certificatesResolvers.letsencrypt.acme]
  email = "{{ USER_MAIL }}"
  storage = "/etc/traefik/certs/acme.json"
  [certificatesResolvers.letsencrypt.acme.httpChallenge]
    entrypoint = "http"
{% endif %}
