# https://hub.docker.com/_/wordpress/tags
WORDPRESS_VERSION: "6.4.2-php8.2"
WORDPRESS_DB_VERSION: "10.11.6" # https://hub.docker.com/_/mariadb/tags
WORDPRESS_FRONT_PORT: "8040"
WORDPRESS_EXTERNAL_URL: "blog.{{ (DOMAIN_NAME |length > 0) | ternary(DOMAIN_NAME, DEFAULT_DOMAIN_NAME) }}"
WORDPRESS_DEFAULT_STATE: stopped
