---
- name: "Setup insolante directory"
  file:
    path: "/{{ DATACORE }}/insolante"
    owner: "{{ USER_NAME }}"
    group: "{{ USER_NAME }}"
    state: directory

- name: "Launch insolante container for ARM {{ INSOLANTE_VERSION }}"
  docker_container:
    name: "insolante"
    image: "ngargaud/insolante:arm-{{ INSOLANTE_VERSION }}"
    state: "{{ INSOLANTE_DEFAULT_STATE }}"
    restart_policy: always
    timeout: "{{ DOCKER_TIMEOUT }}"
    ports:
      - "{{ INSOLANTE_PORT }}:5000"
    env:
      URL: "{{ INSOLANTE_URL }}"
      RPORT: "{{ INSOLANTE_PORT }}"
      DEBUG: "false"
    labels:
      traefik.enable: "{{ INSOLANTE_EXPOSITION }}"
      traefik.http.services.insolante.loadbalancer.server.port: "5000"
      traefik.http.middlewares.https_redirect.redirectscheme.scheme: "https"
      traefik.http.routers.insolante_http.middlewares: "https_redirect"
      traefik.http.routers.insolante_http.rule: "Host(`{{ INSOLANTE_EXTERNAL_URL }}`)"
      traefik.http.routers.insolante_https.rule: "Host(`{{ INSOLANTE_EXTERNAL_URL }}`)"
      traefik.http.routers.insolante_https.tls: "true"
    volumes:
      - "/{{ DATACORE }}/insolante:/opt/core/data"
  when: ansible_architecture in ["armv7l", "aarch64"]

- name: "Launch insolante container for x86_64 {{ INSOLANTE_VERSION }}"
  docker_container:
    name: "insolante"
    image: "ngargaud/insolante:{{ INSOLANTE_VERSION }}"
    state: "{{ INSOLANTE_DEFAULT_STATE }}"
    restart_policy: always
    timeout: "{{ DOCKER_TIMEOUT }}"
    ports:
      - "{{ INSOLANTE_PORT }}:5000"
    env:
      URL: "{{ INSOLANTE_URL }}"
      RPORT: "{{ INSOLANTE_PORT }}"
      DEBUG: "false"
    labels:
      traefik.enable: "{{ INSOLANTE_EXPOSITION }}"
      traefik.http.services.insolante.loadbalancer.server.port: "5000"
      traefik.http.middlewares.https_redirect.redirectscheme.scheme: "https"
      traefik.http.routers.insolante_http.middlewares: "https_redirect"
      traefik.http.routers.insolante_http.rule: "Host(`{{ INSOLANTE_EXTERNAL_URL }}`)"
      traefik.http.routers.insolante_https.rule: "Host(`{{ INSOLANTE_EXTERNAL_URL }}`)"
      traefik.http.routers.insolante_https.tls: "true"
    volumes:
      - "/{{ DATACORE }}/insolante:/opt/core/data"
  when: ansible_architecture in ["amd64", "x86_64"]
