---
- name: "Setup nodered directory"
  file:
    path: "/{{ DATACORE }}/nodered"
    owner: "{{ USER_NAME }}"
    group: "{{ USER_NAME }}"
    state: directory

- name: "Get user ID"
  shell: "id -u {{ USER_NAME }}"
  register: user_id

- name: "Launch nodered container {{ NODERED_VERSION }}"
  docker_container:
    name: "nodered"
    image: "nodered/node-red:{{ NODERED_VERSION }}"
    state: "{{ NODERED_DEFAULT_STATE }}"
    restart_policy: always
    recreate: yes
    timeout: "{{ DOCKER_TIMEOUT }}"
    user: "{{ user_id.stdout }}"
    links:
      - mqtt:mqtt
    ports:
      - "{{ NODERED_FRONT_PORT }}:1880"
    labels:
      traefik.enable: "{{ NODERED_EXPOSITION }}"
      traefik.http.services.nodered.loadbalancer.server.port: "1880"
      traefik.http.middlewares.https_redirect.redirectscheme.scheme: "https"
      traefik.http.routers.nodered_http.middlewares: "https_redirect"
      traefik.http.routers.nodered_http.rule: "Host(`{{ NODERED_EXTERNAL_URL }}`)"
      traefik.http.routers.nodered_https.rule: "Host(`{{ NODERED_EXTERNAL_URL }}`)"
      traefik.http.routers.nodered_https.tls: "true"
    volumes:
      - "/{{ DATACORE }}/nodered:/data"
  become: true
  become_user: "{{ USER_NAME }}"
