BACKUP_MODE: ""
BACKUP_REMOTE_URL: "mafreebox.free.fr"
BACKUP_REMOTE_USER: "freebox"
BACKUP_REMOTE_PATH: "Disque dur/backups"

TRAEFIK_VERSION: "2.2.8"
TRAEFIK_FRONT_PORT: "8000"
TRAEFIK_EXTERNAL_URL: "traefik.{{ DOMAIN_NAME }}"
TRAEFIK_USE_LETSENCRYPT: false
TRAEFIK_CERT_NAME: "forge.local+2"
TRAEFIK_ENTRYPOINT_MAP:
  - { port: "{{ NGINX_FRONT_PORT }}", name: "homepage" }
  - { port: "{{ PORTAINER_PORT }}", name: "portainer" }
  - { port: "{{ NETDATA_PORT }}", name: "netdata" }
  - { port: "{{ GOGS_FRONT_PORT }}", name: "gogs" }
  - { port: "{{ JENKINS_PORT }}", name: "jenkins" }
  - { port: "{{ REDMINE_FRONT_PORT }}", name: "redmine" }
  - { port: "{{ MQTT_FRONT_PORT }}", name: "mqtt" }
  - { port: "{{ NODERED_FRONT_PORT }}", name: "nodered" }
  - { port: "{{ OCTOPRINT_PORT }}", name: "octoprint" }
  - { port: "{{ INSOLANTE_PORT }}", name: "insolante" }

NGINX_VERSION: "1.19.0"
NGINX_FRONT_PORT: "8001"
NGINX_EXTERNAL_URL: "home.{{ DOMAIN_NAME }}"

PORTAINER_VERSION: "1.24.1"
PORTAINER_PORT: "8010"
PORTAINER_EXTERNAL_URL: "portainer.{{ DOMAIN_NAME }}"

NETDATA_VERSION: "v1.23.0"
NETDATA_PORT: "8011"
NETDATA_EXTERNAL_URL: "monitor.{{ DOMAIN_NAME }}"
NETDATA_DEFAULT_STATE: started
