# https://hub.docker.com/r/linuxserver/grocy/tags
GROCY_VERSION: "v4.0.1-ls207"
GROCY_PORT: "8056"
GROCY_EXTERNAL_URL: "stock.{{ (DOMAIN_NAME |length > 0) | ternary(DOMAIN_NAME, DEFAULT_DOMAIN_NAME) }}"
GROCY_DEFAULT_STATE: stopped

# https://hub.docker.com/_/odoo/tags
ODOO_VERSION: "16.0"
ODOO_PORT: "8057"
ODOO_EXTERNAL_URL: "erp.{{ (DOMAIN_NAME |length > 0) | ternary(DOMAIN_NAME, DEFAULT_DOMAIN_NAME) }}"
ODOO_DB_USER: "odoo"
ODOO_DEFAULT_STATE: stopped

# https://hub.docker.com/r/corentinth/it-tools/tags
IT_TOOLS_VERSION: "2023.5.14-77f2efc"
IT_TOOLS_PORT: "8058"
IT_TOOLS_EXTERNAL_URL: "tools.{{ (DOMAIN_NAME |length > 0) | ternary(DOMAIN_NAME, DEFAULT_DOMAIN_NAME) }}"
IT_TOOLS_DEFAULT_STATE: stopped
