---
- import_tasks: prepare_facts.yml
- import_tasks: setup_dependencies.yml
- import_tasks: setup_docker.yml
- import_tasks: setup_security.yml
- import_tasks: setup_user.yml
- import_tasks: setup_access.yml
- import_tasks: setup_nvidia.yml
  when: with_nvidia_gpu is defined
