---
- name: "Display lsb_release informations"
  ansible.builtin.debug:
    var: hostvars[inventory_hostname].ansible_lsb

- name: "Display architecture"
  ansible.builtin.debug:
    var: hostvars[inventory_hostname].ansible_architecture

- name: "Import default variables from identity file ({{ IDENTITY }})"
  ansible.builtin.include_vars: "identity/{{ IDENTITY }}/vars.yml"
  #no_log: true

- name: "Import secret variables from identity file ({{ IDENTITY }})"
  ansible.builtin.include_vars: "identity/{{ IDENTITY }}/vault.yml"
  no_log: true

- name: "Get repository information (url)"
  ansible.builtin.shell: "git remote get-url origin"
  register: git_url
  delegate_to: localhost

- name: "Get repository information (branch)"
  ansible.builtin.shell: "git rev-parse --abbrev-ref HEAD"
  register: git_branch
  delegate_to: localhost

- name: "Get repository information (commit)"
  ansible.builtin.shell: "git rev-parse HEAD"
  register: git_commit
  delegate_to: localhost

- name: "Detect gpu information"
  ansible.builtin.shell: "lspci -v | grep -i vga"
  register: pci_result
  ignore_errors: yes
  no_log: true

- name: "Set with_nvidia_gpu"
  ansible.builtin.set_fact:
    with_nvidia_gpu: true
  when: '"nvidia" in pci_result.stdout|lower'

- name: "Get the apt package facts"
  ansible.builtin.package_facts:
    manager: "auto"

- name: "Add playbook run information on the guest"
  ansible.builtin.copy:
    content: "Ansible informations about the last run\n\n"
    dest: "/root/ansible.info"

- name: "Add playbook information on the guest file"
  ansible.builtin.lineinfile:
    dest: "/root/ansible.info"
    line: "{{ item }}"
  with_items:
    - "* IDENTITY: {{ IDENTITY }}"
    - "* DATACORE: {{ DATACORE }}"
    - "* USER_NAME: {{ USER_NAME }}"
    - "* USER_MAIL: {{ USER_MAIL }}"
    - "* DOMAIN_NAME: {{ (DOMAIN_NAME |length > 0) | ternary(DOMAIN_NAME, DEFAULT_DOMAIN_NAME) }}"
    - "* DEFAULT_ADMIN_NAME: {{ DEFAULT_ADMIN_NAME }}"
    - "* git url: {{ git_url.stdout }}"
    - "* git branch: {{ git_branch.stdout }}"
    - "* git commit: {{ git_commit.stdout }}"

- name: "Define global_proxy_rule"
  ansible.builtin.set_fact:
     global_proxy_rule: "Host(`{{ (DOMAIN_NAME |length > 0) | ternary(DOMAIN_NAME, hostvars[inventory_hostname]['ansible_default_ipv4']['address']) }}`)"

- name: "Check if ldap need to be configured"
  block:
    - name: "Ensure all ldap settings are available"
      ansible.builtin.set_fact:
        configure_ldap: "ready"
      when: LDAP_CONFIGURATION.ldap_remotes | length > 0 and LDAP_CONFIGURATION.ldap_username | length > 0 and LDAP_CONFIGURATION.ldap_password | length > 0 and LDAP_CONFIGURATION.ldap_search | length > 0 and LDAP_CONFIGURATION.ldap_access_group | length > 0 and LDAP_CONFIGURATION.ldap_admin_group | length > 0
    - name: "Show ldap configuration status"
      ansible.builtin.debug:
        var: configure_ldap
  when: LDAP_CONFIGURATION is defined and LDAP_CONFIGURATION.ldap_domain | length > 0
