---
- name: "Check for authorized_keys"
  local_action: stat path=files/authorized_keys
  register: stat_authorized_keys

- name: "Copy authorized_keys for root"
  copy:
    src: "files/authorized_keys"
    dest: "/root/.ssh/authorized_keys"
    owner: "root"
    group: "root"
    mode: u=rw,g=r,o=r
  when: stat_authorized_keys.stat.exists

- name: "Copy authorized_keys for regular user"
  copy:
    src: "files/authorized_keys"
    dest: "/home/{{ USER_NAME }}/.ssh/authorized_keys"
    owner: "{{ USER_NAME }}"
    group: "{{ USER_NAME }}"
    mode: u=rw,g=r,o=r
  when: stat_authorized_keys.stat.exists

- name: "Reset root password"
  user:
    name: "root"
    password: "{{ ROOT_PASS | password_hash('sha512') }}"
    shell: /bin/bash
    update_password: always
