---
- name: "Set regular user parameters"
  ansible.builtin.user:
    name: "{{ USER_NAME }}"
    password: "{{ USER_PASS | password_hash('sha512') }}"
    shell: /bin/bash
    generate_ssh_key: yes
    ssh_key_bits: 2048
    ssh_key_file: .ssh/id_rsa

- name: "Adding existing user '{{ USER_NAME }}' to group sudo"
  ansible.builtin.user:
    name: '{{ USER_NAME }}'
    groups: sudo
    append: yes

- name: "Setup datacore directory"
  ansible.builtin.file:
    path: "/{{ DATACORE }}"
    owner: "{{ USER_NAME }}"
    group: "{{ USER_NAME }}"
    state: directory

- name: "Ensure aliases are present in users profile"
  ansible.builtin.lineinfile:
    path: '/home/{{ USER_NAME }}/.profile'
    line: "{{ item }}"
  with_items:
    - alias ll='ls -alh'
    - alias dpsa='docker ps -a'
    - alias dpsf='docker ps -a --format {% raw %} "{{.Names}} ({{.Image}}) {{.Status}} on {{ .Ports}}" {% endraw %}'
