---
DOMAIN_NAME: ""
DATACORE: "home/{{ USER_NAME }}/data"
DOMAIN_CERT_NAME: ""
DOMAIN_CERT_KEY_NAME: ""
DEFAULT_ADMIN_NAME: "admin"
USER_NAME: "forge"
USER_MAIL: "{{ USER_NAME }}@{{ (DOMAIN_NAME |length > 0) | ternary(DOMAIN_NAME, 'exemple.org') }}"
SKIP_SERVICES: ["peertube", "fdroid", "insolante"]
# uncomment to test the new service
# SKIP_SERVICES: ["peertube", "fdroid", "insolante", "gogs", "jenkins", "redmine", "domotic", "octoprint", "wordpress", "nextcloud", "nexus", "erp", "grocy", "tools", "desk", "label", "audio", "text", "image"]

BACKUP_CONFIGURATION:
  BACKUP_TO_KEEP: 3
  BACKUP_DRIVE: ""
  REMOTE_SERVER: ""
  REMOTE_PATH: ""
  REMOTE_USER: ""

# ==============================================================================
# Text LLM default model
TEXT_LLM_MODEL: ""

# Default stable diffusion webui [invoke | auto | auto-cpu | comfy | comfy-cpu]
IMAGE_WEBUI: "auto"

# ==============================================================================
# Jenkins specific configuration
JENKINS_CONFIGURATION:
  # Select the color of jenkins theme here
  # grey, ed, pink, purple, deep-purple, indigo,
  # blue, light-blue, cyan, teal, green, light-green,
  # lime, yellow, amber, orange, deep-orange, brown, blue-grey
  jenkins_theme_color: "blue-grey"
  jenkins_smtp_host: ""
  jenkins_email_suffix: ""

# You can also specify some global environment variables in jenkins.
JENKINS_EXTRA_GLOBAL_ENV:
    FORGE_MODE: "development"
