INSOLANTE_VERSION: "1.0.0-beta"
INSOLANTE_PORT: 8023
INSOLANTE_URL: "{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}"
INSOLANTE_EXTERNAL_URL: "pcb.{{ DOMAIN_NAME }}"
INSOLANTE_EXPOSITION: "false"

NODERED_VERSION: "0.19.4"
NODERED_FRONT_PORT: 8024
NODERED_EXTERNAL_URL: "flows.{{ DOMAIN_NAME }}"
NODERED_EXPOSITION: "false"

OCTOPRINT_VERSION: "1.3.9"
OCTOPRINT_PORT: 8025
OCTOPRINT_EXTERNAL_URL: "printers.{{ DOMAIN_NAME }}"
OCTOPRINT_EXPOSITION: "false"
