---
- name: "Setup datacore directory"
  file:
    path: "/{{ DATACORE }}/fdroid"
    owner: "{{ USER_NAME }}"
    group: "{{ USER_NAME }}"
    state: directory

- name: "Setup fdroid apk directory"
  file:
    path: "/{{ DATACORE }}/fdroid/apk"
    owner: "{{ USER_NAME }}"
    group: "{{ USER_NAME }}"
    state: directory

- name: "Setup fdroid config directory"
  file:
    path: "/{{ DATACORE }}/fdroid/config"
    owner: "{{ USER_NAME }}"
    group: "{{ USER_NAME }}"
    state: directory

- name: "Check for authorized_keys"
  local_action: stat path=files/authorized_keys
  register: stat_authorized_keys

- name: "Copy authorized_keys for root"
  copy:
    src: "files/fdroid/authorized_keys"
    dest: "/{{ DATACORE }}/fdroid/config/authorized_keys"
    owner: "root"
    group: "root"
    mode: u=rw,g=r,o=r
  when: stat_authorized_keys.stat.exists

- name: "Copy basic configuration for admin credentials"
  template:
    src: "files/fdroid/config.in.py"
    dest: "/{{ DATACORE }}/fdroid/config/config.in.py"
    mode: u=rw,g=r,o=r

- name: "Define fdroid_image ARM?"
  set_fact:
     fdroid_image: "ngargaud/fdroid-server:arm-{{ FDROID_VERSION }}"
  when: ansible_architecture in ["armv7l", "aarch64"]

- name: "Define fdroid_image amd64?"
  set_fact:
     fdroid_image: "ngargaud/fdroid-server:{{ FDROID_VERSION }}"
  when: ansible_architecture in ["amd64", "x86_64"]

- name: "Launch fdroid container {{ FDROID_VERSION }}"
  docker_container:
    name: "fdroid"
    hostname: "fdroid"
    image: "{{ fdroid_image }}"
    state: "{{FDROID_DEFAULT_STATE }}"
    restart_policy: always
    recreate: yes
    timeout: "{{ DOCKER_TIMEOUT }}"
    ports:
#      - "{{ FDROID_PORT }}:80"
      - "{{ FDROID_SSH_PORT }}:22"
    volumes:
      - "/{{ DATACORE }}/fdroid/apk:/opt/apk"
      - "/{{ DATACORE }}/fdroid/config:/opt/config"
    labels:
      traefik.enable: "true"
      traefik.http.services.fdroid.loadbalancer.server.port: "80"
      traefik.http.middlewares.https_redirect.redirectscheme.scheme: "https"
      traefik.http.routers.fdroid_http.middlewares: "https_redirect"
      traefik.http.routers.fdroid_http.rule: "Host(`{{ FDROID_EXTERNAL_URL }}`)"
      traefik.http.routers.fdroid_http.service: fdroid
      traefik.http.routers.fdroid_https.rule: "Host(`{{ FDROID_EXTERNAL_URL }}`)"
      traefik.http.routers.fdroid_https.service: fdroid
      traefik.http.routers.fdroid_https.tls: "true"
      # add this to use traefik as a proxy with tls (http will not be available)
      traefik.http.services.fdroid_proxy.loadbalancer.server.port: "80"
      traefik.http.routers.fdroid_proxy.service: fdroid_proxy
      traefik.http.routers.fdroid_proxy.entrypoints: fdroid
      traefik.http.routers.fdroid_proxy.rule: "{{ global_proxy_rule }}"
      traefik.http.routers.fdroid_proxy.tls: "true"
  when: fdroid_image is defined
