- Infrastructure:
    - Traefik:
        container: traefik
        icon: si-traefikproxy
        href: http://{{ HOMEPAGE_DOMAIN }}:{{ TRAEFIK_FRONT_PORT }}
        description: "HTTPS support and reverse proxy with domain name."
        target: _blank
    - Portainer:
        container: portainer
        icon: si-portainer
        href: https://{{ HOMEPAGE_DOMAIN }}:{{ PORTAINER_PORT }}
        description: "Docker images manager."
        target: _blank
    - Homepage:
        container: traefik
        icon: mdi-home-automation
        href: https://{{ HOMEPAGE_DOMAIN }}:{{ HOMEPAGE_FRONT_PORT }}
        description: "A highly customizable homepage (or startpage / application dashboard) with Docker and service API integrations."
        target: _blank
    - Netdata:
        container: netdata
        icon: si-grafana
        href: https://{{ HOMEPAGE_DOMAIN }}:{{ NETDATA_PORT }}
        description: "The open-source, real-time, performance and health monitoring."
        target: _blank
- Development:
    - Gogs:
        container: gogs
        icon: si-git
        href: https://{{ HOMEPAGE_DOMAIN }}:{{ GOGS_FRONT_PORT }}
        description: "Github like server, source storage (lighter than gitlab), git port on {{ GOGS_SSH_PORT | default('unknown') }}."
        target: _blank
    - Jenkins:
        container: jenkins
        icon: si-jenkins
        href: https://{{ HOMEPAGE_DOMAIN }}:{{ JENKINS_PORT }}
        description: "The leading open source automation server."
        target: _blank
    - Redmine:
        container: redmine
        icon: si-redmine
        href: https://{{ HOMEPAGE_DOMAIN }}:{{ REDMINE_FRONT_PORT }}
        description: "A highly customizable homepage (or startpage / application dashboard) with Docker and service API integrations."
        target: _blank
- Hardware:
    - MQTT:
        container: mqtt
        icon: si-mqtt
        href: https://{{ HOMEPAGE_DOMAIN }}:{{ MQTT_FRONT_PORT }}
        description: "Mosquitto broker for the Internet of Things (Using websocket)."
        target: _blank
    - Nodered:
        container: nodered
        icon: si-nodered
        href: https://{{ HOMEPAGE_DOMAIN }}:{{ NODERED_FRONT_PORT }}
        description: "Flow-based programming for the Internet of Things."
        target: _blank
    - Octoprint:
        container: octoprint
        icon: si-octoprint
        href: https://{{ HOMEPAGE_DOMAIN }}:{{ OCTOPRINT_PORT }}
        description: "The snappy web interface for your 3D printer."
        target: _blank
    - Insolante:
        container: insolante
        icon: mdi-printer-3d
        href: https://{{ HOMEPAGE_DOMAIN }}:{{ INSOLANTE_PORT }}
        description: "Gerber to gcode converter (wrapper to pcb2gcode)."
        target: _blank
- Social:
    - WordPress:
        container: wordpress
        icon: si-wordpress
        href: https://{{ HOMEPAGE_DOMAIN }}:{{ WORDPRESS_FRONT_PORT }}
        description: "The WordPress rich content management system."
        target: _blank
- Storage:
    - Nexus:
        container: nexus
        icon: mdi-nas
        href: https://{{ HOMEPAGE_DOMAIN }}:{{ NEXUS_PORT }}
        description: "Artifact manager and docker registry (push: {{ NEXUS_DOCKER_PUSH_PORT | default('unknown') }}, pull: {{ NEXUS_DOCKER_PULL_PORT | default('unknown') }})"
        target: _blank
    - F-droid:
        container: fdroid
        icon: si-fdroid
        href: https://{{ HOMEPAGE_DOMAIN }}:{{ FDROID_PORT }}
        description: "Android application server (with scp access through {{ FDROID_SSH_PORT | default('unknown') }})."
        target: _blank
- Productivity:
    - Grocy:
        container: grocy
        icon: si-grocy
        href: https://{{ HOMEPAGE_DOMAIN }}:{{ GROCY_PORT }}
        description: "ERP beyond your fridge - grocy is a web-based self-hosted groceries & household management solution for your home."
        target: _blank
    - It-tools:
        container: tools
        icon: mdi-tools
        href: https://{{ HOMEPAGE_DOMAIN }}:{{ IT_TOOLS_PORT }}
        description: "Useful tools for developer and people working in IT."
        target: _blank
- MachineLearning:
    - Label-studio:
        container: label_studio
        icon: mdi-label-multiple
        href: https://{{ HOMEPAGE_DOMAIN }}:{{ LABEL_STUDIO_PORT }}
        description: "Label Studio is a multi-type data labeling and annotation tool with standardized output format."
        target: _blank
    - Audio-webui:
        container: audio_webui
        icon: mdi-music
        href: https://{{ HOMEPAGE_DOMAIN }}:{{ AUDIO_WEBUI_PORT }}
        description: "A webui for different audio related Neural Networks."
        target: _blank
    - Text-webui:
        container: text_webui
        icon: mdi-script-text-play-outline
        href: https://{{ HOMEPAGE_DOMAIN }}:{{ TEXT_WEBUI_PORT }}
        description: "A Gradio web UI for Large Language Models. Supports transformers, GPTQ, llama.cpp (ggml), Llama models. (api on {{ TEXT_WEBUI_API_PORT | default('unknown') }}, stream on {{ TEXT_WEBUI_STEAM_PORT | default('unknown') }})"
        target: _blank
    - Image-webui:
        container: image_webui
        icon: mdi-image-edit
        href: https://{{ HOMEPAGE_DOMAIN }}:{{ IMAGE_WEBUI_PORT }}
        description: "Easy Docker setup for Stable Diffusion with user-friendly UI ."
        target: _blank
    - Ollama:
        container: ollama
        icon: mdi-script-text-play-outline
        href: https://{{ HOMEPAGE_DOMAIN }}:{{ OLLAMA_API_PORT }}
        description: "The easiest way to get up and running with large language models locally. Server API"
        target: _blank
