---
- name: "Setup label-studio directory"
  ansible.builtin.file:
    path: "{{ item }}"
    owner: "1001"
    group: "1001"
    state: directory
  with_items:
    - "/{{ DATACORE }}/label-studio"

- name: "Launch label-studio container {{ LABEL_STUDIO_VERSION }}"
  community.general.docker_container:
    name: "label_studio"
    image: "heartexlabs/label-studio:{{ LABEL_STUDIO_VERSION }}"
    state: "{{ LABEL_STUDIO_DEFAULT_STATE }}"
    restart_policy: always
    recreate: yes
    timeout: "{{ DOCKER_TIMEOUT }}"
#    ports:
#      - "{{ LABEL_STUDIO_PORT }}:8080"
    volumes:
      - "/{{ DATACORE }}/label-studio:/label-studio/data"
    labels:
      traefik.enable: "true"
      traefik.http.services.label_studio.loadbalancer.server.port: "8080"
      traefik.http.middlewares.https_redirect.redirectscheme.scheme: "https"
      traefik.http.routers.label_studio_http.middlewares: "https_redirect"
      traefik.http.routers.label_studio_http.rule: "Host(`{{ LABEL_STUDIO_EXTERNAL_URL }}`)"
      traefik.http.routers.label_studio_http.service: label_studio
      traefik.http.routers.label_studio_https.rule: "Host(`{{ LABEL_STUDIO_EXTERNAL_URL }}`)"
      traefik.http.routers.label_studio_https.service: label_studio
      traefik.http.routers.label_studio_https.tls: "true"
      # add this to use traefik as a proxy with tls (http will not be available)
      traefik.http.services.label_studio_proxy.loadbalancer.server.port: "8080"
      traefik.http.routers.label_studio_proxy.service: label_studio_proxy
      traefik.http.routers.label_studio_proxy.entrypoints: label_studio
      traefik.http.routers.label_studio_proxy.rule: "{{ global_proxy_rule }}"
      traefik.http.routers.label_studio_proxy.tls: "true"
