---
- name: "Setup wordpress database directory"
  file:
    path: "/{{ DATACORE }}/wordpress_db"
    owner: "{{ USER_NAME }}"
    group: "{{ USER_NAME }}"
    state: directory

- name: "Setup wordpress directory"
  file:
    path: "/{{ DATACORE }}/wordpress"
    owner: "{{ USER_NAME }}"
    group: "{{ USER_NAME }}"
    state: directory

- name: "Launch mysql container for wordpress"
  docker_container:
    name: "wordpress_db"
    image: "arm64v8/mariadb:{{ WORDPRESS_DB_VERSION }}"
    state: started
    restart_policy: always
    recreate: yes
    env:
      MYSQL_ROOT_HOST: "%"
      MYSQL_ROOT_PASSWORD: "{{ WORDPRESS_DB_PASS }}_root"
      MYSQL_PASSWORD: "{{ WORDPRESS_DB_PASS }}"
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
    volumes:
      - "/{{ DATACORE }}/wordpress_db:/var/lib/mysql"
  when: ansible_architecture in ["aarch64"]

- name: "wait"
  pause:
    minutes: 5

- name: "Launch wordpress container"
  docker_container:
    name: "wordpress"
    image: "arm32v7/wordpress:{{ WORDPRESS_VERSION }}"
    state: started
    restart_policy: always
    recreate: yes
    links:
      - wordpress_db:wordpress_db
    ports:
      - "{{ WORDPRESS_FRONT_PORT }}:80"
    env:
      WORDPRESS_DB_PASSWORD: "{{ WORDPRESS_DB_PASS }}"
      WORDPRESS_DB_HOST: wordpress_db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_NAME: wordpress
    labels:
      traefik.port: "80"
      traefik.enable: "{{ WORDPRESS_EXPOSITION }}"
      traefik.frontend.rule: "Host:{{ WORDPRESS_EXTERNAL_URL }}"
    volumes:
      - "/{{ DATACORE }}/wordpress:/var/www"
  when: ansible_architecture in ["armv7l", "aarch64"]
