GOGS_VERSION: "0.12.3"
GOGS_FRONT_PORT: "8021"
GOGS_SSH_PORT: "{{ GIT_SSH_PORT }}"
GOGS_EXTERNAL_URL: "git.{{ (DOMAIN_NAME |length > 0) | ternary(DOMAIN_NAME, DEFAULT_DOMAIN_NAME) }}"
GOGS_URL: "https://{{ (DOMAIN_NAME |length > 0) | ternary(DOMAIN_NAME, hostvars[inventory_hostname]['ansible_default_ipv4']['address']) }}:{{ GOGS_FRONT_PORT }}"
GOGS_DEFAULT_STATE: stopped

REDMINE_VERSION: "4.2.3"
REDMINE_DB_VERSION: "10-alpine"
REDMINE_DB_USER: "redmine_user"
REDMINE_DB_PASS: "redmine_pass"
REDMINE_DB_NAME: "redmine"
REDMINE_FRONT_PORT: "8024"
REDMINE_EXTERNAL_URL: "redmine.{{ (DOMAIN_NAME |length > 0) | ternary(DOMAIN_NAME, DEFAULT_DOMAIN_NAME) }}"
REDMINE_DEFAULT_STATE: stopped

# Use https://updates.jenkins-ci.org/download/war/ to get the version package checksum
JENKINS_VERSION: "2.320"
JENKINS_SHA_256: "b847cf68825f2b81bd41981177b87e8e8ffa18a708085901c38f7ed2518f9027"
JENKINS_PORT_CONFIG: 9000
JENKINS_PORT: "8023"
JENKINS_EXTERNAL_URL: "ci.{{ (DOMAIN_NAME |length > 0) | ternary(DOMAIN_NAME, DEFAULT_DOMAIN_NAME) }}"
JENKINS_DEFAULT_STATE: stopped
JENKINS_USER: "{{ DEFAULT_ADMIN_NAME }}"
JENKINS_RESTART_DELAY: 100
JENKINS_FORGE_GLOBAL_ENV:
  gogs_repositories_url: "{{ (DOMAIN_NAME |length > 0) | ternary(DOMAIN_NAME, hostvars[inventory_hostname]['ansible_default_ipv4']['address']) }}:{{ GOGS_SSH_PORT }}"
  nexus_repositories_url: "{{ (DOMAIN_NAME |length > 0) | ternary(DOMAIN_NAME, hostvars[inventory_hostname]['ansible_default_ipv4']['address']) }}:{{ NEXUS_PORT }}"
  nexus_docker_pull_url: "{{ (DOMAIN_NAME |length > 0) | ternary(DOMAIN_NAME, hostvars[inventory_hostname]['ansible_default_ipv4']['address']) }}:{{ NEXUS_DOCKER_PULL_PORT }}"
  nexus_docker_push_url: "{{ (DOMAIN_NAME |length > 0) | ternary(DOMAIN_NAME, hostvars[inventory_hostname]['ansible_default_ipv4']['address']) }}:{{ NEXUS_DOCKER_PUSH_PORT }}"
  fdroid_apk_push_url: "{{ (DOMAIN_NAME |length > 0) | ternary(DOMAIN_NAME, hostvars[inventory_hostname]['ansible_default_ipv4']['address']) }}:{{ FDROID_SSH_PORT }}"
JENKINS_FORGE_CREDENTIALS:
  fdroid_deploy_key:
    private_key: "{{ FDROID_DEPLOY.private_key }}"
    username: "{{ FDROID_DEPLOY.username }}"
  nexus_docker_credentials:
    username: "{{ NEXUS_DEPLOY.username }}"
    password: "{{ NEXUS_DEPLOY.password }}"
  nexus_pip_credentials:
    username: "{{ NEXUS_DEPLOY.username }}"
    password: "{{ NEXUS_DEPLOY.password }}"
  nexus_npm_credentials:
    username: "{{ NEXUS_DEPLOY.username }}"
    password: "{{ NEXUS_DEPLOY.password }}"
  nexus_raw_credentials:
    username: "{{ NEXUS_DEPLOY.username }}"
    password: "{{ NEXUS_DEPLOY.password }}"
