# https://hub.docker.com/r/gogs/gogs/tags
GOGS_VERSION: "0.13.0"
GOGS_FRONT_PORT: "8021"
GOGS_SSH_PORT: "{{ GIT_SSH_PORT }}"
GOGS_EXTERNAL_URL: "git.{{ (DOMAIN_NAME |length > 0) | ternary(DOMAIN_NAME, DEFAULT_DOMAIN_NAME) }}"
GOGS_URL: "https://{{ (DOMAIN_NAME |length > 0) | ternary(DOMAIN_NAME, hostvars[inventory_hostname]['ansible_default_ipv4']['address']) }}:{{ GOGS_FRONT_PORT }}"
GOGS_DEFAULT_STATE: stopped

# https://hub.docker.com/_/redmine/tags
REDMINE_VERSION: "5.1.1"
REDMINE_DB_VERSION: "10-alpine"
REDMINE_DB_USER: "redmine_user"
REDMINE_DB_PASS: "redmine_pass"
REDMINE_DB_NAME: "redmine"
REDMINE_FRONT_PORT: "8024"
REDMINE_EXTERNAL_URL: "redmine.{{ (DOMAIN_NAME |length > 0) | ternary(DOMAIN_NAME, DEFAULT_DOMAIN_NAME) }}"
REDMINE_DEFAULT_STATE: stopped

# https://hub.docker.com/r/jenkins/jenkins/tags
JENKINS_VERSION: "2.436-jdk17"
JENKINS_PORT_CONFIG: 9000
JENKINS_PORT: "8023"
JENKINS_EXTERNAL_URL: "ci.{{ (DOMAIN_NAME |length > 0) | ternary(DOMAIN_NAME, DEFAULT_DOMAIN_NAME) }}"
JENKINS_DEFAULT_STATE: stopped
JENKINS_USER: "{{ DEFAULT_ADMIN_NAME }}"
JENKINS_RESTART_DELAY: 100
JENKINS_ENABLE_THEME: true
JENKINS_FORGE_GLOBAL_ENV:
  gogs_repositories_url: "{{ (DOMAIN_NAME |length > 0) | ternary(DOMAIN_NAME, hostvars[inventory_hostname]['ansible_default_ipv4']['address']) }}:{{ GOGS_SSH_PORT }}"
  nexus_repositories_url: "{{ (DOMAIN_NAME |length > 0) | ternary(DOMAIN_NAME, hostvars[inventory_hostname]['ansible_default_ipv4']['address']) }}:{{ NEXUS_PORT }}"
  nexus_docker_pull_url: "{{ (DOMAIN_NAME |length > 0) | ternary(DOMAIN_NAME, hostvars[inventory_hostname]['ansible_default_ipv4']['address']) }}:{{ NEXUS_DOCKER_PULL_PORT }}"
  nexus_docker_push_url: "{{ (DOMAIN_NAME |length > 0) | ternary(DOMAIN_NAME, hostvars[inventory_hostname]['ansible_default_ipv4']['address']) }}:{{ NEXUS_DOCKER_PUSH_PORT }}"
  fdroid_apk_push_url: "{{ (DOMAIN_NAME |length > 0) | ternary(DOMAIN_NAME, hostvars[inventory_hostname]['ansible_default_ipv4']['address']) }}:{{ FDROID_SSH_PORT }}"
JENKINS_FORGE_CREDENTIALS:
  fdroid_deploy_key:
    private_key: "{{ FDROID_DEPLOY.private_key }}"
    username: "{{ FDROID_DEPLOY.username }}"
  nexus_docker_credentials:
    username: "{{ NEXUS_DEPLOY.username }}"
    password: "{{ NEXUS_DEPLOY.password }}"
  nexus_pip_credentials:
    username: "{{ NEXUS_DEPLOY.username }}"
    password: "{{ NEXUS_DEPLOY.password }}"
  nexus_npm_credentials:
    username: "{{ NEXUS_DEPLOY.username }}"
    password: "{{ NEXUS_DEPLOY.password }}"
  nexus_raw_credentials:
    username: "{{ NEXUS_DEPLOY.username }}"
    password: "{{ NEXUS_DEPLOY.password }}"
