---
- name: "Setup datacore directory"
  ansible.builtin.file:
    path: "/{{ DATACORE }}/{{ item }}"
    owner: "{{ USER_NAME }}"
    group: "{{ USER_NAME }}"
    state: directory
  with_items:
    - onlyoffice
    - onlyoffice/data
    - onlyoffice/logs
    - onlyoffice/certs
    - onlyoffice/postgresql

- name: "Launch onlyoffice container {{ ONLYOFFICE_VERSION }}"
  community.general.docker_container:
    name: "onlyoffice"
    hostname: "onlyoffice"
    image: "onlyoffice/documentserver:{{ ONLYOFFICE_VERSION }}"
    state: "{{ONLYOFFICE_DEFAULT_STATE }}"
    restart_policy: always
    recreate: yes
    timeout: "{{ DOCKER_TIMEOUT }}"
    ports:
#      - "{{ ONLYOFFICE_PORT }}:80"
    env:
      JWT_ENABLED: "false"
    volumes:
      - "/{{ DATACORE }}/onlyoffice/logs:/var/log/onlyoffice"
      - "/{{ DATACORE }}/onlyoffice/data:/var/lib/onlyoffice"
      - "/{{ DATACORE }}/onlyoffice/postgresql:/var/lib/postgresql"
      - "/{{ DATACORE }}/onlyoffice/certs:/var/www/onlyoffice/Data"
    labels:
      traefik.enable: "true"
      traefik.http.services.onlyoffice.loadbalancer.server.port: "8000"
      traefik.http.middlewares.https_redirect.redirectscheme.scheme: "https"
      traefik.http.routers.onlyoffice_http.middlewares: "https_redirect"
      traefik.http.routers.onlyoffice_http.rule: "Host(`{{ ONLYOFFICE_EXTERNAL_URL }}`)"
      traefik.http.routers.onlyoffice_http.service: onlyoffice
      traefik.http.routers.onlyoffice_https.rule: "Host(`{{ ONLYOFFICE_EXTERNAL_URL }}`)"
      traefik.http.routers.onlyoffice_https.service: onlyoffice
      traefik.http.routers.onlyoffice_https.tls: "true"
      # add this to use traefik as a proxy with tls (http will not be available)
      traefik.http.services.onlyoffice_proxy.loadbalancer.server.port: "8000"
      traefik.http.routers.onlyoffice_proxy.service: onlyoffice_proxy
      traefik.http.routers.onlyoffice_proxy.entrypoints: onlyoffice
      traefik.http.routers.onlyoffice_proxy.rule: "{{ global_proxy_rule }}"
      traefik.http.routers.onlyoffice_proxy.tls: "true"
