---
- name: "Launch it-tools container {{ IT_TOOLS_VERSION }}"
  community.general.docker_container:
    name: "tools"
    image: "corentinth/it-tools:{{ IT_TOOLS_VERSION }}"
    state: "{{ IT_TOOLS_DEFAULT_STATE }}"
    restart_policy: always
    recreate: yes
    timeout: "{{ DOCKER_TIMEOUT }}"
#    ports:
#      - "{{ IT_TOOLS_PORT }}:80"
    labels:
      traefik.enable: "true"
      traefik.http.services.it_tools.loadbalancer.server.port: "80"
      traefik.http.middlewares.https_redirect.redirectscheme.scheme: "https"
      traefik.http.routers.it_tools_http.middlewares: "https_redirect"
      traefik.http.routers.it_tools_http.rule: "Host(`{{ IT_TOOLS_EXTERNAL_URL }}`)"
      traefik.http.routers.it_tools_http.service: it_tools
      traefik.http.routers.it_tools_https.rule: "Host(`{{ IT_TOOLS_EXTERNAL_URL }}`)"
      traefik.http.routers.it_tools_https.service: it_tools
      traefik.http.routers.it_tools_https.tls: "true"
      # add this to use traefik as a proxy with tls (http will not be available)
      traefik.http.services.it_tools_proxy.loadbalancer.server.port: "80"
      traefik.http.routers.it_tools_proxy.service: it_tools_proxy
      traefik.http.routers.it_tools_proxy.entrypoints: it_tools
      traefik.http.routers.it_tools_proxy.rule: "{{ global_proxy_rule }}"
      traefik.http.routers.it_tools_proxy.tls: "true"
