---
- name: "Setup nextcloud directory"
  file:
    path: "{{ item }}"
    owner: "33"
    group: "33"
    state: directory
  with_items:
    - "/{{ DATACORE }}/nextcloud"
    - "/{{ DATACORE }}/nextcloud/apps"
    - "/{{ DATACORE }}/nextcloud/config"
    - "/{{ DATACORE }}/nextcloud/data"

- name: "Launch nextcloud container {{ NEXTCLOUD_VERSION }}"
  docker_container:
    name: "nextcloud"
    image: "nextcloud:{{ NEXTCLOUD_VERSION }}"
    state: "{{NEXTCLOUD_DEFAULT_STATE }}"
    restart_policy: always
    recreate: yes
    timeout: "{{ DOCKER_TIMEOUT }}"
    ports:
      - "{{ NEXTCLOUD_PORT }}:80"
    env:
      SQLITE_DATABASE: "1"
      NEXTCLOUD_ADMIN_USER: "{{ DEFAULT_ADMIN_NAME }}"
      NEXTCLOUD_ADMIN_PASSWORD: "{{ NEXTCLOUD_PASS }}"
      NEXTCLOUD_TRUSTED_DOMAINS: "{{ NEXTCLOUD_URL_IN_CONFIG }} {{ NEXTCLOUD_EXTERNAL_URL }} localhost"
    labels:
      traefik.enable: "{{ NEXTCLOUD_EXPOSITION }}"
      traefik.http.services.nextcloud.loadbalancer.server.port: "80"
      traefik.http.middlewares.https_redirect.redirectscheme.scheme: "https"
      traefik.http.routers.nextcloud_http.middlewares: "https_redirect"
      traefik.http.routers.nextcloud_http.rule: "Host(`{{ NEXTCLOUD_EXTERNAL_URL }}`)"
      traefik.http.routers.nextcloud_https.rule: "Host(`{{ NEXTCLOUD_EXTERNAL_URL }}`)"
      traefik.http.routers.nextcloud_https.tls: "true"
    volumes:
      - "/{{ DATACORE }}/nextcloud:/var/www/html"
      - "/{{ DATACORE }}/nextcloud/apps:/var/www/html/custom_apps"
      - "/{{ DATACORE }}/nextcloud/config:/var/www/html/config"
      - "/{{ DATACORE }}/nextcloud/data:/var/www/html/data"
