# from: https://www.sheevaboite.fr/articles/traefik-reverse-proxy-https-containers-docker
- name: "Setup traefik directory"
  file:
    path: "/{{ DATACORE }}/traefik"
    owner: "{{ USER_NAME }}"
    group: "{{ USER_NAME }}"
    state: directory

- name: "Copy traefik configuration in traefik directory"
  template:
    src: files/traefik/traefik.tml
    dest: "/{{ DATACORE }}/traefik/traefik.toml"
    owner: "{{ USER_NAME }}"
    group: "{{ USER_NAME }}"
    mode: 0644

- name: "Launch traefik container for ARM {{ TRAEFIK_VERSION }}"
  docker_container:
    name: "traefik"
    image: "arm32v6/traefik:{{ TRAEFIK_VERSION }}"
    command: --api --docker --metrics --ping --logLevel=INFO
    state: started
    restart_policy: always
    recreate: yes
    ports:
      - "80:80"
      - "443:443"
      - "{{ TRAEFIK_FRONT_PORT }}:8080"
    labels:
      traefik.port: "8080"
      traefik.enable: "{{ TRAEFIK_EXPOSITION }}"
      traefik.frontend.rule: "Host:{{ TRAEFIK_EXTERNAL_URL }}"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "/{{ DATACORE }}/traefik/certs/:/certs/"
      - "/{{ DATACORE }}/traefik:/etc/traefik"
  when: ansible_architecture in ["armv6l", "armv7l", "aarch64"]

- name: "Launch traefik container for x64 {{ TRAEFIK_VERSION }}"
  docker_container:
    name: "traefik"
    image: "traefik:{{ TRAEFIK_VERSION }}"
    command: --api --docker --metrics --ping --logLevel=INFO
    state: started
    restart_policy: always
    recreate: yes
    ports:
      - "80:80"
      - "443:443"
      - "{{ TRAEFIK_FRONT_PORT }}:8080"
    labels:
      traefik.port: "8080"
      traefik.enable: "{{ TRAEFIK_EXPOSITION }}"
      traefik.frontend.rule: "Host:{{ TRAEFIK_EXTERNAL_URL }}"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "/{{ DATACORE }}/traefik/certs/:/certs/"
      - "/{{ DATACORE }}/traefik:/etc/traefik"
  when: ansible_architecture in ["amd64", "x86_64"]

- name: "Sleep for 30 seconds to let traefik starts"
  wait_for: timeout=30
  delegate_to: localhost

- name: "Make sure the certificate file has the correct rights"
  file:
    path: "/{{ DATACORE }}/traefik/acme.json"
    owner: "root"
    group: "root"
    mode: 0600
