---
- name: "Setup home page directory"
  file:
    path: "/{{ DATACORE }}/homepage"
    owner: "{{ USER_NAME }}"
    group: "{{ USER_NAME }}"
    state: directory

- name: "Install page template"
  template:
    src: files/homepage/{{ item }}
    dest: "/{{ DATACORE }}/homepage/{{ item }}"
    owner: "{{ USER_NAME }}"
    group: "{{ USER_NAME }}"
    mode: 0644
  with_items:
    - index.html
    - services.json

- name: "Launch homepage nginx container {{ NGINX_VERSION }}"
  docker_container:
    name: "homepage"
    image: "nginx:{{ NGINX_VERSION }}"
    state: started
    restart_policy: always
    recreate: yes
    timeout: "{{ DOCKER_TIMEOUT }}"
    ports:
      - "{{ NGINX_FRONT_PORT }}:80"
    labels:
      traefik.enable: "{{ NGINX_EXPOSITION }}"
      traefik.http.services.nginx.loadbalancer.server.port: "80"
      traefik.http.middlewares.https_redirect.redirectscheme.scheme: "https"
      traefik.http.routers.nginx_http.middlewares: "https_redirect"
      traefik.http.routers.nginx_http.rule: "Host(`{{ NGINX_EXTERNAL_URL }}`)"
      traefik.http.routers.nginx_https.rule: "Host(`{{ NGINX_EXTERNAL_URL }}`)"
      traefik.http.routers.nginx_https.tls: "true"
    volumes:
      - "/{{ DATACORE }}/homepage:/usr/share/nginx/html:ro"
