# from: https://www.sheevaboite.fr/articles/traefik-reverse-proxy-https-containers-docker
- name: "Setup traefik directory"
  file:
    path: "/{{ DATACORE }}/traefik"
    owner: "{{ USER_NAME }}"
    group: "{{ USER_NAME }}"
    state: directory

- name: "Copy traefik configuration in traefik directory"
  copy:
    src: files/traefik/traefik.tml
    dest: "/{{ DATACORE }}/traefik/traefik.toml"
    owner: "{{ USER_NAME }}"
    group: "{{ USER_NAME }}"
    mode: 0644

- name: "Check for files/crypted_acme.json"
  local_action: stat path=roles/infra/tasks/files/crypted_acme.json
  register: stat_local_certificate

- name: "Install certificate if it exists"
  copy:
    src: files/traefik/crypted_acme.json
    dest: "/{{ DATACORE }}/traefik/acme.json"
    owner: "root"
    group: "root"
    backup: yes
    decrypt: yes
    mode: 0600
  when: stat_local_certificate.stat.exists == true

- name: "Launch traefik container for ARM {{ TRAEFIK_VERSION }}"
  docker_container:
    name: "traefik"
    image: "arm32v6/traefik:{{ TRAEFIK_VERSION }}"
    command: --api --docker --metrics --ping --logLevel=INFO
    state: started
    restart_policy: always
    recreate: yes
    ports:
      - "80:80"
      - "443:443"
      - "{{ TRAEFIK_FRONT_PORT }}:8080"
    labels:
      traefik.enable: "false"
      traefik.port: "8080"
      traefik.frontend.rule: "Host:traefik.{{ DOMAIN_NAME }}"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "/{{ DATACORE }}/traefik/certs/:/certs/"
      - "/{{ DATACORE }}/traefik:/etc/traefik"
  when: ansible_architecture == "armv7l" or ansible_architecture == "armv6l"

- name: "Launch traefik container for x64 {{ TRAEFIK_VERSION }}"
  docker_container:
    name: "traefik"
    image: "traefik:{{ TRAEFIK_VERSION }}"
    command: --api --docker --metrics --ping --logLevel=INFO
    state: started
    restart_policy: always
    recreate: yes
    ports:
      - "80:80"
      - "443:443"
      - "{{ TRAEFIK_FRONT_PORT }}:8080"
    labels:
      traefik.enable: "false"
      traefik.port: "8080"
      traefik.frontend.rule: "Host:traefik.{{ DOMAIN_NAME }}"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "/{{ DATACORE }}/traefik/certs/:/certs/"
      - "/{{ DATACORE }}/traefik:/etc/traefik"
  when: ansible_architecture == "amd64" or ansible_architecture == "x86_64"

- name: "Make sure the certificate file has the correct rights"
  file:
    path: "/{{ DATACORE }}/traefik/acme.json"
    owner: "root"
    group: "root"
    mode: 0600

- name: "Sleep for 30 seconds to let traefik starts"
  wait_for: timeout=30
  delegate_to: localhost
