---
- name: "Get docker group ID"
  shell: "grep docker /etc/group | cut -d ':' -f 3"
  register: docker_id

- name: "Create netdata container for ARM {{ NETDATA_VERSION }} (stopped)"
  docker_container:
    name: "netdata"
    image: "netdata/netdata:{{ NETDATA_VERSION }}-armhf"
    state: "{{ NETDATA_DEFAULT_STATE }}"
    restart_policy: always
    recreate: yes
    timeout: "{{ DOCKER_TIMEOUT }}"
    ports:
      - "{{ NETDATA_PORT }}:19999"
    volumes:
      - "/proc:/host/proc:ro"
      - "/sys:/host/sys:ro"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    capabilities:
      - SYS_PTRACE
    env:
      PGID: "{{ docker_id.stdout }}"
    labels:
      traefik.enable: "{{ NETDATA_EXPOSITION }}"
      traefik.http.services.netdata.loadbalancer.server.port: "19999"
      traefik.http.middlewares.https_redirect.redirectscheme.scheme: "https"
      traefik.http.routers.netdata_http.middlewares: "https_redirect"
      traefik.http.routers.netdata_http.rule: "Host(`{{ NETDATA_EXTERNAL_URL }}`)"
      traefik.http.routers.netdata_https.rule: "Host(`{{ NETDATA_EXTERNAL_URL }}`)"
      traefik.http.routers.netdata_https.tls: "true"
  when: ansible_architecture in ["armv7l", "aarch64"]

- name: "Launch netdata container {{ NETDATA_VERSION }}"
  docker_container:
    name: "netdata"
    image: "netdata/netdata:{{ NETDATA_VERSION }}"
    state: "{{ NETDATA_DEFAULT_STATE }}"
    restart_policy: always
    recreate: yes
    timeout: "{{ DOCKER_TIMEOUT }}"
    ports:
      - "{{ NETDATA_PORT }}:19999"
    volumes:
      - "/proc:/host/proc:ro"
      - "/sys:/host/sys:ro"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    capabilities:
      - SYS_PTRACE
    labels:
      traefik.enable: "{{ NETDATA_EXPOSITION }}"
      traefik.http.services.netdata.loadbalancer.server.port: "19999"
      traefik.http.middlewares.https_redirect.redirectscheme.scheme: "https"
      traefik.http.routers.netdata_http.middlewares: "https_redirect"
      traefik.http.routers.netdata_http.rule: "Host(`{{ NETDATA_EXTERNAL_URL }}`)"
      traefik.http.routers.netdata_https.rule: "Host(`{{ NETDATA_EXTERNAL_URL }}`)"
      traefik.http.routers.netdata_https.tls: "true"
  when: ansible_architecture in ["amd64", "x86_64"]
