- name: "Install duplicity"
  apt:
    pkg: [lftp, duplicity]
    state: present
    update_cache: true
    cache_valid_time: 3600

- name: "Create local backup before update"
  shell: "tar cvpzf /home/{{ USER_NAME }}/data_{{ FORGE_MODE }}_ansible_backup.tar.gz /{{ DATACORE }}"

- name: "Copy backup task template in cron.d"
  copy:
    src: files/backup/backup_cron_base.sh
    dest: /etc/cron.d/duplicity.full
    owner: root
    group: root
    mode: 0500

- name: "Add the line to backup the datacore in the cron script"
  lineinfile:
    path: /etc/cron.d/duplicity.full
    line: "PASSPHRASE='{{ BACKUP_PASS }}' duplicity full -v 9 --rsync-options='-p' /{{ DATACORE }} 'ftp://{{ BACKUP_REMOTE_USER }}:{{ BACKUP_REMOTE_PASS }}@{{ BACKUP_REMOTE_URL }}/{{ BACKUP_REMOTE_PATH }}/{{ FORGE_MODE }}'"

- name: "Add a line to delete old backups in the cron script"
  lineinfile:
    path: /etc/cron.d/duplicity.full
    line: "PASSPHRASE='{{ BACKUP_PASS }}' duplicity remove-all-but-n-full 3 --force 'ftp://{{ BACKUP_REMOTE_USER }}:{{ BACKUP_REMOTE_PASS }}@{{ BACKUP_REMOTE_URL }}/{{ BACKUP_REMOTE_PATH }}/{{ FORGE_MODE }}'"

- name: "Add full backup task in crontab"
  cron:
    name: full duplicity
    minute: "0"
    hour: "5"
    user: root
    job: /etc/cron.d/duplicity.full

- name: "Create initial remote backup before update"
  shell: "/etc/cron.d/duplicity.full"
  when: BACKUP_MODE == "create"

- name: "Restore last remote backup before recontruction"
  shell: "rm -rf /{{ DATACORE }} && PASSPHRASE='{{ BACKUP_PASS }}' duplicity restore --rsync-options='-p' 'ftp://{{ BACKUP_REMOTE_USER }}:{{ BACKUP_REMOTE_PASS }}@{{ BACKUP_REMOTE_URL }}/{{ BACKUP_REMOTE_PATH }}/{{ FORGE_MODE }}' /{{ DATACORE }}"
  when: BACKUP_MODE == "restore"
