---
- import_tasks: prepare_facts.yml
- import_tasks: setup_host_dependencies.yml
- import_tasks: setup_security.yml
- import_tasks: setup_user.yml
  when: ("vault" in FEATURES)
- import_tasks: setup_access.yml
  when: ("vault" in FEATURES)
