---
- name: "Display lsb_release informations"
  debug:
    var: hostvars[inventory_hostname].ansible_lsb

- name: "Display architecture"
  debug:
    var: hostvars[inventory_hostname].ansible_architecture

- name: "Import secret variables from vault file ({{ FORGE_MODE }})"
  include_vars: "vault_{{ FORGE_MODE }}.yml"
  no_log: true

- name: "Get repository information (url)"
  shell: "git remote get-url origin"
  register: git_url
  delegate_to: localhost
  vars:
    ansible_python_interpreter: python

- name: "Get repository information (branch)"
  shell: "git rev-parse --abbrev-ref HEAD"
  register: git_branch
  delegate_to: localhost
  vars:
    ansible_python_interpreter: python

- name: "Get repository information (commit)"
  shell: "git rev-parse HEAD"
  register: git_commit
  delegate_to: localhost
  vars:
    ansible_python_interpreter: python

- name: "Get the apt package facts"
  package_facts:
    manager: "auto"

- name: "Add playbook run information on the guest"
  copy:
    content: "Ansible informations about the last run\n\n"
    dest: "/root/ansible.info"

- name: "Add playbook information on the guest file"
  lineinfile:
    dest: "/root/ansible.info"
    line: "{{ item }}"
  with_items:
    - "* FORGE_MODE: {{ FORGE_MODE }}"
    - "* DATACORE: {{ DATACORE }}"
    - "* USER_NAME: {{ USER_NAME }}"
    - "* USER_MAIL: {{ USER_MAIL }}"
    - "* DOMAIN_NAME: {{ DOMAIN_NAME }}"
    - "* DEFAULT_ADMIN_NAME: {{ DEFAULT_ADMIN_NAME }}"
    - "* git url: {{ git_url.stdout }}"
    - "* git branch: {{ git_branch.stdout }}"
    - "* git commit: {{ git_commit.stdout }}"

- name: "Define global_proxy_rule"
  set_fact:
     global_proxy_rule: "Host(`{{ inventory_hostname }}`) || Host(`{{ DOMAIN_NAME }}`) || Host(`{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}`)"
