---
- name: "Install python and python-pip"
  apt:
    pkg: [python2.7, python3-pip, apt-transport-https, ca-certificates, curl, software-properties-common, htop]
    state: present
    update_cache: true
    cache_valid_time: 3600

- name: "Install pip packages"
  pip:
    name: [docker-py, passlib, setuptools]

- name: "Install docker"
  shell: curl -sSL https://get.docker.com | sh
  when: '"docker-ce" not in ansible_facts.packages'

- name: "Ensure docker service exec command is correct"
  ini_file:
    path: "/lib/systemd/system/docker.service"
    section: Service
    option: ExecStart
    value: "/usr/bin/dockerd --icc -H unix://"
  register: docker_config_update

- name: Reload and restart service docker
  service:
    name: docker
    state: restarted
    daemon_reload : yes
  when: docker_config_update.changed
