---
- import_tasks: setup_gogs.yml
  when: ("gogs" in FEATURES)

- import_tasks: setup_jenkins.yml
  when: ("jenkins" in FEATURES) and ("vault" in FEATURES) and ansible_architecture in ["aarch64", "amd64", "x86_64"]

- import_tasks: setup_jenkins_plugins.yml
  when: ("jenkins" in FEATURES) and ("vault" in FEATURES) and ansible_architecture in ["aarch64", "amd64", "x86_64"]

- import_tasks: setup_redmine.yml
  when: ("redmine" in FEATURES)
