- hosts: forge
  gather_facts: yes
  any_errors_fatal: true
  max_fail_percentage: 0
  serial: 100%
  vars:
  - IDENTITY: "dev"
  - SKIP_SERVICES: []
  roles:
    - common
    - infra
    - infra_ci
    - infra_hard
    - infra_social
    - infra_storage
