- hosts: forge
  gather_facts: yes
  any_errors_fatal: true
  max_fail_percentage: 0
  serial: 100%
  vars:
  - IDENTITY: "dev"
  roles:
    - common
    - infra
    - infra_ci
    - infra_ml
    - infra_hard
    - infra_social
    - infra_storage
    - infra_productivity
