---
- import_tasks: setup_backup.yml
  when: BACKUP_MODE in ["create", "restore_remote"]

- import_tasks: setup_https.yml
- import_tasks: setup_portainer.yml
- import_tasks: setup_homepage.yml
- import_tasks: setup_netdata.yml
