---
- name: "Install duplicity"
  ansible.builtin.apt:
    pkg: [lftp, duplicity]
    state: present
    update_cache: true
    cache_valid_time: 3600

- name: "Copy backup task template in cron.d"
  ansible.builtin.template:
    src: files/backup/backup.full
    dest: /etc/cron.d/backup.full
    owner: root
    group: root
    mode: 0500

- name: "Add full backup task in crontab"
  ansible.builtin.cron:
    name: "full backup run"
    minute: "0"
    hour: "5"
    user: root
    job: /etc/cron.d/backup.full

- name: "Create initial remote backup before update in '{{ IDENTITY }}'"
  ansible.builtin.shell: "/etc/cron.d/backup.full"
  when: BACKUP_MODE == "create"

- name: "Restore last remote backup before recontruction from '{{ IDENTITY }}'"
  ansible.builtin.shell: "rm -rf /{{ DATACORE }} && PASSPHRASE='{{ BACKUP_PASS }}' duplicity restore --rsync-options='-p' 'ftp://{{ BACKUP_REMOTE_USER }}:{{ BACKUP_REMOTE_PASS }}@{{ BACKUP_REMOTE_URL }}/{{ BACKUP_REMOTE_PATH }}/{{ IDENTITY }}' /{{ DATACORE }}"
  when: BACKUP_MODE == "restore_remote"
