BACKUP_MODE: "{{ lookup('env','BACKUP_MODE') | default('') }}"
BACKUP_TO_KEEP: "{{ BACKUP_CONFIGURATION.BACKUP_TO_KEEP | default(3) }}"
BACKUP_REMOTE_URL: "{{ BACKUP_CONFIGURATION.REMOTE_SERVER }}"
BACKUP_REMOTE_PATH: "{{ BACKUP_CONFIGURATION.REMOTE_PATH }}"
BACKUP_REMOTE_USER: "{{ BACKUP_CONFIGURATION.REMOTE_USER }}"
BACKUP_DRIVE: "{{ BACKUP_CONFIGURATION.BACKUP_DRIVE }}"
BACKUP_TOKEN: "{{ BACKUP_CONFIGURATION.BACKUP_TOKEN }}"

# https://hub.docker.com/r/arm32v6/traefik/tags
TRAEFIK_VERSION: "2.11"
TRAEFIK_FRONT_PORT: "8000"
TRAEFIK_EXTERNAL_URL: "traefik.{{ (DOMAIN_NAME |length > 0) | ternary(DOMAIN_NAME, DEFAULT_DOMAIN_NAME) }}"
TRAEFIK_USE_LETSENCRYPT: false
TRAEFIK_ENTRYPOINT_MAP:
  - { port: "{{ HOMEPAGE_FRONT_PORT }}", name: "homepage" }
  - { port: "{{ PORTAINER_PORT }}", name: "portainer" }
  - { port: "{{ NETDATA_PORT }}", name: "netdata" }
  - { port: "{{ GOGS_FRONT_PORT }}", name: "gogs" }
  - { port: "{{ JENKINS_PORT }}", name: "jenkins" }
  - { port: "{{ REDMINE_FRONT_PORT }}", name: "redmine" }
  - { port: "{{ MQTT_FRONT_PORT }}", name: "mqtt" }
  - { port: "{{ NODERED_FRONT_PORT }}", name: "nodered" }
  - { port: "{{ OCTOPRINT_PORT }}", name: "octoprint" }
  - { port: "{{ INSOLANTE_PORT }}", name: "insolante" }
  - { port: "{{ WORDPRESS_FRONT_PORT }}", name: "wordpress" }
  - { port: "{{ NEXUS_PORT }}", name: "nexus" }
  - { port: "{{ NEXUS_DOCKER_PULL_PORT }}", name: "nexus_docker_pull" }
  - { port: "{{ NEXUS_DOCKER_PUSH_PORT }}", name: "nexus_docker_push" }
  - { port: "{{ FDROID_PORT }}", name: "fdroid" }
  - { port: "{{ GROCY_PORT }}", name: "grocy" }
  - { port: "{{ NOTEBOOK_PORT }}", name: "notebook" }
  - { port: "{{ IT_TOOLS_PORT }}", name: "it_tools" }
  - { port: "{{ LABEL_STUDIO_PORT }}", name: "label_studio" }
  - { port: "{{ AUDIO_WEBUI_PORT }}", name: "audio_webui" }
  - { port: "{{ TEXT_WEBUI_PORT }}", name: "text_webui" }
  - { port: "{{ TEXT_WEBUI_API_PORT }}", name: "text_webui_api" }
  - { port: "{{ TEXT_WEBUI_STEAM_PORT }}", name: "text_webui_stream" }
  - { port: "{{ IMAGE_WEBUI_PORT }}", name: "image_webui" }
  - { port: "{{ OLLAMA_API_PORT }}", name: "ollama" }

HOMEPAGE_VERSION: "latest"
HOMEPAGE_FRONT_PORT: "8001"
HOMEPAGE_EXTERNAL_URL: "home.{{ (DOMAIN_NAME |length > 0) | ternary(DOMAIN_NAME, DEFAULT_DOMAIN_NAME) }}"
HOMEPAGE_DOMAIN: "{{ (DOMAIN_NAME |length > 0) | ternary(DOMAIN_NAME, hostvars[inventory_hostname]['ansible_default_ipv4']['address']) }}"

# https://hub.docker.com/r/portainer/portainer-ce/tags
PORTAINER_VERSION: "2.19.4-alpine"
PORTAINER_PORT: "8010"
PORTAINER_EXTERNAL_URL: "portainer.{{ (DOMAIN_NAME |length > 0) | ternary(DOMAIN_NAME, DEFAULT_DOMAIN_NAME) }}"

# https://hub.docker.com/r/netdata/netdata/tags
NETDATA_VERSION: "v1.44.1"
NETDATA_PORT: "8011"
NETDATA_EXTERNAL_URL: "monitor.{{ (DOMAIN_NAME |length > 0) | ternary(DOMAIN_NAME, DEFAULT_DOMAIN_NAME) }}"
NETDATA_DEFAULT_STATE: stopped
