BACKUP_MODE: "{{ lookup('env','BACKUP_MODE') | default('') }}"
BACKUP_TO_KEEP: "{{ BACKUP_CONFIGURATION.BACKUP_TO_KEEP | default(3) }}"
BACKUP_REMOTE_URL: "{{ BACKUP_CONFIGURATION.REMOTE_SERVER }}"
BACKUP_REMOTE_PATH: "{{ BACKUP_CONFIGURATION.REMOTE_PATH }}"
BACKUP_REMOTE_USER: "{{ BACKUP_CONFIGURATION.REMOTE_USER }}"
BACKUP_DRIVE: "{{ BACKUP_CONFIGURATION.BACKUP_DRIVE }}"
BACKUP_TOKEN: "{{ BACKUP_CONFIGURATION.BACKUP_TOKEN }}"

TRAEFIK_VERSION: "2.6.1"
TRAEFIK_FRONT_PORT: "8000"
TRAEFIK_EXTERNAL_URL: "traefik.{{ (DOMAIN_NAME |length > 0) | ternary(DOMAIN_NAME, DEFAULT_DOMAIN_NAME) }}"
TRAEFIK_USE_LETSENCRYPT: false
TRAEFIK_ENTRYPOINT_MAP:
  - { port: "{{ NGINX_FRONT_PORT }}", name: "homepage" }
  - { port: "{{ PORTAINER_PORT }}", name: "portainer" }
  - { port: "{{ NETDATA_PORT }}", name: "netdata" }
  - { port: "{{ GOGS_FRONT_PORT }}", name: "gogs" }
  - { port: "{{ JENKINS_PORT }}", name: "jenkins" }
  - { port: "{{ REDMINE_FRONT_PORT }}", name: "redmine" }
  - { port: "{{ MQTT_FRONT_PORT }}", name: "mqtt" }
  - { port: "{{ NODERED_FRONT_PORT }}", name: "nodered" }
  - { port: "{{ OCTOPRINT_PORT }}", name: "octoprint" }
  - { port: "{{ INSOLANTE_PORT }}", name: "insolante" }
  - { port: "{{ WORDPRESS_FRONT_PORT }}", name: "wordpress" }
  - { port: "{{ PEERTUBE_PORT }}", name: "peertube" }
  - { port: "{{ NEXUS_PORT }}", name: "nexus" }
  - { port: "{{ NEXUS_DOCKER_PULL_PORT }}", name: "nexus_docker_pull" }
  - { port: "{{ NEXUS_DOCKER_PUSH_PORT }}", name: "nexus_docker_push" }
  - { port: "{{ FDROID_PORT }}", name: "fdroid" }
  - { port: "{{ NEXTCLOUD_PORT }}", name: "nextcloud" }
  - { port: "{{ GROCY_PORT }}", name: "grocy" }
  - { port: "{{ ODOO_PORT }}", name: "odoo" }

NGINX_VERSION: "1.21.6"
NGINX_FRONT_PORT: "8001"
NGINX_EXTERNAL_URL: "home.{{ (DOMAIN_NAME |length > 0) | ternary(DOMAIN_NAME, DEFAULT_DOMAIN_NAME) }}"

PORTAINER_VERSION: "2.11.1-alpine"
PORTAINER_PORT: "8010"
PORTAINER_EXTERNAL_URL: "portainer.{{ (DOMAIN_NAME |length > 0) | ternary(DOMAIN_NAME, DEFAULT_DOMAIN_NAME) }}"

NETDATA_VERSION: "v1.33.1"
NETDATA_PORT: "8011"
NETDATA_EXTERNAL_URL: "monitor.{{ (DOMAIN_NAME |length > 0) | ternary(DOMAIN_NAME, DEFAULT_DOMAIN_NAME) }}"
NETDATA_DEFAULT_STATE: stopped
