---
- import_tasks: setup_wordpress.yml
  when: ("wordpress" not in SKIP_SERVICES) and ansible_architecture in ["aarch64", "amd64", "x86_64"]

- import_tasks: setup_peertube.yml
  when: ("peertube" not in SKIP_SERVICES) and ansible_architecture in ["aarch64", "amd64", "x86_64"]
